# Generated by Django 4.2.1 on 2023-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
