# Generated by Django 4.2.1 on 2023-06-10 13:38

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_musiclist_title_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[posts.models.validate_rating]),
        ),
    ]
