# Generated by Django 4.2.1 on 2023-06-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('posts', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclist',
            name='projects',
            field=models.ManyToManyField(to='projects.project'),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
