# Generated by Django 4.2.1 on 2023-06-28 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_alter_musiclist_projects_alter_musiclist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, validators=[posts.models.validate_like_dislike])),
                ('is_fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, validators=[posts.models.validate_like_dislike])),
                ('is_fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='listfavourite',
            name='music_list',
        ),
        migrations.RemoveField(
            model_name='listfavourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listupvote',
            name='music_list',
        ),
        migrations.RemoveField(
            model_name='listupvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewdownvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewdownvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewfavourite',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewfavourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewupvote',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewupvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='is_disliked',
        ),
        migrations.RemoveField(
            model_name='musiclist',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_disliked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='musiclist',
            name='like_dislike',
            field=models.IntegerField(default=0, validators=[posts.models.validate_like_dislike]),
        ),
        migrations.AddField(
            model_name='review',
            name='like_dislike',
            field=models.IntegerField(default=0, validators=[posts.models.validate_like_dislike]),
        ),
        migrations.DeleteModel(
            name='ListDownvote',
        ),
        migrations.DeleteModel(
            name='ListFavourite',
        ),
        migrations.DeleteModel(
            name='ListUpvote',
        ),
        migrations.DeleteModel(
            name='ReviewDownvote',
        ),
        migrations.DeleteModel(
            name='ReviewFavourite',
        ),
        migrations.DeleteModel(
            name='ReviewUpvote',
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='posts.review'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listvote',
            name='music_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='posts.musiclist'),
        ),
        migrations.AddField(
            model_name='listvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
