# Generated by Django 4.2.1 on 2023-07-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_listvote_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcommentvote',
            name='is_fav',
        ),
        migrations.RemoveField(
            model_name='reviewcommentvote',
            name='is_fav',
        ),
    ]
