# Generated by Django 4.2.1 on 2023-07-08 23:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_listcommentvote_is_fav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True, validators=[posts.models.validate_rating]),
        ),
    ]
