# Generated by Django 4.2.1 on 2023-07-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_review_body_alter_review_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclist',
            name='projects',
        ),
        migrations.AddField(
            model_name='musiclist',
            name='projects',
            field=models.CharField(default='item 1,item2', max_length=100),
            preserve_default=False,
        ),
    ]
