# Generated by Django 4.2.1 on 2023-07-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_artist_created_at_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.artist'),
        ),
    ]
