# Generated by Django 4.2.1 on 2023-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist2',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('artists', models.ManyToManyField(to='projects.artist')),
            ],
        ),
    ]
