# Generated by Django 4.2.1 on 2023-07-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='artist',
            name='ext_id',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ext_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
