# Generated by Django 4.2.1 on 2023-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_artist_created_at_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ext_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ext_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
