# Generated by Django 4.2.1 on 2023-07-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_artist2_project2'),
        ('projects', '0006_alter_artist_ext_id_alter_project_ext_id'),
    ]

    operations = [
    ]
