# Generated by Django 4.2.1 on 2023-07-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_merge_20230708_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist2',
        ),
        migrations.DeleteModel(
            name='Project2',
        ),
    ]
