# Generated by Django 4.2.1 on 2023-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifytoken_spotify_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(default='default', max_length=150),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='spotify_username',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
