# Generated by Django 4.2.1 on 2023-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_alter_spotifytoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='spotify_user',
            field=models.CharField(max_length=190, null=True, unique=True),
        ),
    ]
