# Generated by Django 4.2.1 on 2023-07-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='spotify_user',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
