# Generated by Django 4.2.1 on 2023-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='spotify_user',
            new_name='session_id',
        ),
    ]
