# Generated by Django 4.2.1 on 2023-05-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reviewer_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
