# Generated by Django 4.2.1 on 2023-05-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_name_reviewer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='name',
            new_name='display_name',
        ),
    ]
