# Generated by Django 4.2.1 on 2023-05-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='user',
            new_name='username',
        ),
    ]
