# Generated by Django 4.2.1 on 2023-05-28 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_user_reviewer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='username',
            new_name='user',
        ),
    ]
